apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- web-deployment.yaml
- web-service.yaml
- web-ingress.yaml
- db-deployment.yaml
- db-service.yaml
- db-persistentvolumeclaim.yaml
commonLabels:
  project: netdash
namePrefix: netdash-
secretGenerator:
- name: secrets
  files:
  - secret/DATABASES
  - secret/NETDASH_FEEDBACK_EMAIL
  - secret/NETDASH_LOGGING
  - secret/DJANGO_SETTINGS_MODULE
  - secret/NETDASH_ALLOWED_HOSTS
  - secret/POSTGRESQL_ADMIN_PASSWORD
  - secret/NETDASH_DEBUG
  - secret/NETDASH_MODULES  # Replace this in an overlay to specify your modules.
  - secret/NETDASH_SECRET_KEY  # Replace this in an overlay for best security practices. See: https://docs.djangoproject.com/en/dev/ref/settings/#secret-key
  type: Opaque
